const config = {
    // タイマーの基本設定（秒）
    TIMER_DURATION: 180,

    // ブロックの数
    TOTAL_BLOCKS: 180,
    BLOCKS_PER_MINUTE: 60,
    TOTAL_MINUTES: 3,

    // アニメーションの時間（ミリ秒）
    FADE_OUT_DURATION: 500,
    FALLBACK_FADE_OUT_DURATION: 300,
    PULSE_DURATION: 300,
    BOUNCE_DURATION: 600,
    COLOR_CHANGE_DURATION: 500,
    MULTIPLE_COLOR_CHANGE_DELAY: 100,
    CELEBRATION_DURATION: 1000,
    CHAIN_ANIMATION_DELAY: 50,
    PROGRESS_ANIMATION_DURATION: 300,
};
